#!/usr/bin/env python3
"""AI Trending Weekly Generator"""

import json
import subprocess
from datetime import datetime, timedelta
import urllib.request
import urllib.parse
import os

REPO_DIR = "/home/node/.openclaw/workspace/ai-trending-daily"
TOKEN = os.environ.get("GITHUB_TOKEN")
DATE = datetime.now().strftime("%Y-%m-%d")
FILENAME = f"week-{DATE}.md"

def run_cmd(cmd):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=REPO_DIR)
    return result.stdout + result.stderr

if not TOKEN:
    print("Error: GITHUB_TOKEN environment variable not set")
    exit(1)

# Calculate date 90 days ago
days_ago = (datetime.now() - timedelta(days=90)).strftime("%Y-%m-%d")

# Build query
query = f"ai OR ml OR llm OR gpt OR agent OR rag created:>{days_ago} stars:>1000"
query_encoded = urllib.parse.quote(query)

url = f"https://api.github.com/search/repositories?q={query_encoded}&sort=stars&order=desc&per_page=10"

req = urllib.request.Request(url)
req.add_header("Authorization", f"token {TOKEN}")
req.add_header("Accept", "application/vnd.github.v3+json")

print("Fetching trending repos...")

with urllib.request.urlopen(req) as response:
    data = json.loads(response.read().decode())

# Generate markdown
md = f"""# AI Weekly Trending - {DATE}

> Generated by OpenClaw

## Top GitHub AI/ML Projects This Week (Created Last 3 Months)

| Project | Description | Stars |
|---------|-------------|-------|
"""

for item in data.get("items", [])[:10]:
    name = item.get("full_name", "")
    desc = item.get("description", "No description") or "No description"
    desc = desc.replace("|", "\\|").replace("\n", " ")
    stars = item.get("stargazers_count", 0)
    md += f"| [{name}]({item.get('html_url')}) | {desc} | {stars} |\n"

md += """
---
*Auto-generated every Sunday*
"""

# Write file
with open(f"{REPO_DIR}/{FILENAME}", "w") as f:
    f.write(md)

print(f"Generated {FILENAME}")

# Update README
readme = """# AI 项目周报

每周一自动收集 GitHub 上周最热门的 AI 新项目。

## 周报列表

"""

import glob
for f in sorted(glob.glob(f"{REPO_DIR}/week-*.md"), reverse=True):
    fname = f.split("/")[-1]
    readme += f"- [{fname}](./{fname})\n"

readme += """
---

*本仓库由 OpenClaw 自动维护*
"""

with open(f"{REPO_DIR}/README.md", "w") as f:
    f.write(readme)

# Git commit and push
run_cmd("git add -A")
run_cmd(f'git commit -m "Update AI trending for week of {DATE}"')
run_cmd("git push origin master")

print("Done!")
